### ISSUE TITLE
Any plans to support video generation?

### ISSUE THREAD

**Issue by mirix** [william-murray1204/stable-diffusion-cpp-python#4]
Any plans to support video generation?

I don't know if this is even remotely related to the SD architecture:

https://huggingface.co/genmo/mochi-1-preview

https://huggingface.co/Kijai/Mochi_preview_comfy/tree/main

**Comment by william-murray1204** [comment]
Hi @mirix, as this project only provides Python bindings for **@leejet's** [`stable-diffusion.cpp`](https://github.com/leejet/stable-diffusion.cpp) library, video generation (of any kind) will first need to be supported in that library. Once it's working there, you’ll be able to use it with this package. 

It's worth noting there is an `img2vid` function in the stable-diffusion.cpp code ([seen here](https://github.com/leejet/stable-diffusion.cpp/blob/ac54e0076052a196b7df961eb1f792c9ff4d7f22/stable-diffusion.h#L187)), however I don't think it works.

Unfortunately im not familiar with the [genmo/mochi-1-preview](https://huggingface.co/genmo/mochi-1-preview) architecture so I cant really give you a good answer as to whether it has any similarity to SD. I'd suggest asking this question in the [`stable-diffusion.cpp`](https://github.com/leejet/stable-diffusion.cpp) repo, although it seems you already have anyway.
